host: localhost:3000
info:
  contact: {}
  description: Crypto-to-Fiat and Fiat-to-Crypto converter
  title: C2F F2C Converter
  version: "1.0"
paths:
  /convert:
    get:
      description: convert fiat to crypto or vise versa
      parameters:
      - description: From Currency
        example: BTC
        in: query
        name: from
        required: true
        type: string
      - description: To Currency
        example: USD
        in: query
        name: to
        required: true
        type: string
      - description: From Currency
        example: 3.1
        in: query
        name: amount
        type: number
      responses:
        "200":
          description: "3.4"
          schema:
            type: string
        "400":
          description: 'invalid conversion for pair: CNY/EUR'
          schema:
            type: string
      summary: Convert given C2F or F2C
      tags:
      - converter
swagger: "2.0"
